### ISSUE TITLE
"Hunger & Health"."No Hunger" Not working on servers

### ISSUE THREAD

**Issue by FernoXL** [Insane-96/IguanaTweaksReborn#300] opened 2024-06-21 23:07 UTC
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.1
* IguanaTweaks Reborn: 3.12.0
* InsaneLib: 1.13.5

**What Happens**:  
Setting the "Hunger & Health"."No Hunger" settings in the common.toml to false does not register on servers.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**debug.log / Crash reports**:  
debug Log with bare minimum mods: https://pastebin.com/TvUF7iFP
debug Log with all used mods: https://gist.github.com/FernoXL/3eedaf6addf8fb87556d69d46d587b3b

//If different from default
**Config**:  
https://pastebin.com/qiLFNqtR

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes.

**Comment by Insane96** [comment] 2024-06-22 06:19
Duplicate of #296

**Closed as completed by Insane96** 2024-06-22 06:19 UTC
Labels: bug
