### ISSUE TITLE
[1.18] Game crashes mentioning that '"insane96mcp.iguanatweaksreborn.module.Modules.combat" is null' when other mods are missing dependencies

### ISSUE THREAD

**Issue by GeorgeOrwell1** [Insane-96/IguanaTweaksReborn#210] opened 2022-02-07 15:51 UTC
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft: 1.18.1
* Forge: 39.0.66
* IguanaTweaks Reborn: 2.9.1
* InsaneLib: 1.4.3

**What Happens**:  
Explain what's the problem
When I start Minecraft with your mod installed as well as [Creeper Overhaul](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul) (+ a couple of other mods) the game instantly crashes on startup.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  [crash-2022-02-07_16.39.14-client.txt](https://github.com/Insane96/IguanaTweaksReborn/files/8016625/crash-2022-02-07_16.39.14-client.txt)

//If different from default
**Config**:  
[https://pastebin.com/hPiKFcej](https://pastebin.com/hPiKFcej)

**Can be reproduced with a minimal set of mods? (E.g. IguanaTweaks Reborn + InsaneLib + Allurement) only?**:  
Yes/No
No, if I only use IguanaTweaks Reborn + InsaneLib it doesn't crash (see crash report for mods list). IguanaTweaks Reborn conflicts with the Creeper Overhaul mod (as stated earlier).

**Comment by Insane96** [comment] 2022-02-07 15:54
Update Forge. Duplicate of #209

**Closed as completed** 2022-02-07 15:55 UTC
Labels: bug, confirmed

**Comment by GeorgeOrwell1** [comment] 2022-02-07 17:56
How am I supposed to update Forge if I already have the latest version lol.

**Comment by Insane96** [comment] 2022-02-07 18:32
Then I don't know how the other guy solved it. It's impossible that "stats" is null unless the game crashes before but my mod pops out.

**Comment by Klouver-github** [comment] 2022-02-12 01:59
I am having the same issue right now

**Comment by Mp5cz** [comment] 2022-03-04 18:48
I just got this crash as well and managed to fix it as well. The actual problem seems to be missing dependencies or wrong forge version, it's just giving a misleading error message when you have iguana installed. If you're having this issue just double check if you have the correct dependencies / forge version or just remove iguana for a sec, launch the game and it should tell you the actual problem.
